import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/components/modal-provider';
import { ToasterProvider } from '@/components/toaster-provider';
import { Toaster } from '@/components/ui/toaster';
import { CrispProvider } from '@/components/crisp-provider';

const font = Montserrat ({ weight: '600', subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Genro_AI',
  description: 'Generated by AI Saas',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <CrispProvider/>
        <body className={font.className}>
          <ToasterProvider/>
          <ModalProvider/>
          {children}
          <Toaster/>
      </body>
      </html>
    </ClerkProvider>
  )
}
