import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

const font = Montserrat ({ weight: '600', subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Genro_AI',
  description: 'Generated by AI Saas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={font.className}>
        
          {children}
       
      </body>
      </html>
    </ClerkProvider>
  )
}
